# Generated by Django 4.0.2 on 2022-03-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.CharField(max_length=255),
        ),
    ]
