# Generated by Django 4.0.2 on 2022-03-02 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.CharField(max_length=60)),
                ('height', models.CharField(max_length=60)),
                ('deep', models.CharField(max_length=60)),
                ('weight', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('wattage', models.CharField(max_length=60)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shoes.brand')),
                ('size', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='electronics.size')),
            ],
        ),
    ]
