# Generated by Django 4.0.2 on 2022-03-07 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=60)),
                ('frequency', models.CharField(max_length=10)),
                ('core', models.IntegerField()),
                ('thread', models.IntegerField()),
                ('brand', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=60)),
                ('capacity', models.CharField(max_length=60)),
                ('bus', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('drive', models.CharField(max_length=255)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='laptops.cpu')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='laptops.ram')),
            ],
        ),
    ]
