# Generated by Django 4.0.2 on 2022-03-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=60)),
                ('rom', models.CharField(max_length=60)),
                ('cardSlot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('display', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=60)),
                ('memories', models.ManyToManyField(to='mobile_phones.Memory')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mobile_phones.producer')),
            ],
        ),
    ]
